In [1]:
import numpy as np

4.1 NumPy ndarray：多维数组对象

In [8]:
# 生成 ndarray
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1)
print(arr1.shape)

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print(arr2.shape)

# 创建全零数组
print(np.zeros(10))
print(np.zeros((5,2)))

# 创建全1数组
print(np.ones((2,3,4)))

# 创建没有初始化值的数组
print(np.empty((3,3)))

[6.  7.5 8.  0.  1. ]
(5,)
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.58884832e-321]
 [1.60218491e-306 0.00000000e+000 0.00000000e+000]]


ndarray 布尔索引：python 的关键字and 和or 对布尔值数组并没有用，请使用&(and)和|(or)来代替

In [4]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

mask = (names == 'Bob') | (names == 'Will')
print(data[mask])

[[ 1.00994092  1.26822397  1.01682237 -0.06743057]
 [ 0.08258203 -0.29590411 -0.11379658  0.29019993]
 [ 0.40714727  0.46606411 -0.26864735 -1.39699538]
 [ 0.67702758  0.52978081 -2.18328679 -0.45532447]]


4.1.6 神奇索引

In [5]:
arr = np.empty((8, 4))

for i in range(8):
    arr[i] = i
print(arr)

# 为了选出一个符合特定顺序的自己，可以简单地通过传递一个包含知名所需顺序的列表或者数组来完成
print(arr[[4, 3, 0, 6]])
# 使用负的索引，蒋从尾部进行选择：
print(arr[[-1, -3, -2]])

# 传递多个索引数组时情况有些许不同，这样会根据每个索引元组所对应的元素选出一个一维数组：
arr = np.arrange

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]


4.3 使用数组进行面向数组编程
    meshgrid(x, y)的作用是产生一个以向量为行，向量y为列的矩阵。

In [7]:
points = np.arange(-5, 5, 0.01)  # 1000 equally spaces points
xs, ys = np.meshgrid(points, points)
print(xs)
print(ys)

z = np.sqrt(xs ** 2 + ys ** 2)

# 可视化二维数组
import matplotlib.pyplot as plt

plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("mage plot of $\{x^2 + y^2}$ for a grid of values")

[[-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 ...
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]]
[[-5.   -5.   -5.   ... -5.   -5.   -5.  ]
 [-4.99 -4.99 -4.99 ... -4.99 -4.99 -4.99]
 [-4.98 -4.98 -4.98 ... -4.98 -4.98 -4.98]
 ...
 [ 4.97  4.97  4.97 ...  4.97  4.97  4.97]
 [ 4.98  4.98  4.98 ...  4.98  4.98  4.98]
 [ 4.99  4.99  4.99 ...  4.99  4.99  4.99]]


Text(0.5,1,'mage plot of $\\{x^2 + y^2}$ for a grid of values')

numpy当中axis的值表示的是这个多维数组维度的下标，比如有一个二维数组a，a的shape是(5,6)，也就是说a有5行6列，axis=0表示的就是[5,6]中的第一维，
也就是行，axis=1表示的是[5,6]中的第二个维度，也就是列。

In [12]:
arr = np.arange(24)
arr = arr.reshape((4,6))

print(arr)
print(arr.sum(axis = 0))
print(arr.sum(axis = 1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[36 40 44 48 52 56]
[ 15  51  87 123]


数组排序

In [15]:
large_arr = np.random.randn(10)
print(large_arr)

large_arr.sort()
print(large_arr)

large_arr[int(0.5 * len(large_arr))]

[-0.64447611 -0.66309318 -0.7100235   0.84011809 -0.36370952  1.20353812
  1.28907974  0.58132118 -0.35328938 -0.9254533 ]
[-0.9254533  -0.7100235  -0.66309318 -0.64447611 -0.36370952 -0.35328938
  0.58132118  0.84011809  1.20353812  1.28907974]


-0.35328937965859253

线性代数：

In [35]:
X = np.random.randn(5,5)
print(X)

mat = np.dot(X.T, X)
print(mat)

X_n = np.linalg.inv(mat)  # 矩阵的逆
print(X_n)

print(np.diag(mat))  # 对角线元素
print(np.diag(np.diag(mat))) # 创建除对角线 全部为0的矩阵

print(np.trace(mat)) # 计算矩阵对角线元素之和

mat_det = np.linalg.det(mat) # 计算矩阵的行列式
print(mat_det)

w, v = np.linalg.eig(mat) # 计算矩阵的特征值和特征向量
print(w)
print(v)

q, r = np.linalg.qr(mat) # 计算矩阵的QR分解

u, s, v = np.linalg.svd(mat) # 计算矩阵的奇异值分解(SVD)

A = np.array([[1, 2, 1], [2, -1, 3], [3, 1, 2]])
B = np.array([7, 7, 18])
x = np.linalg.solve(A, B) # 求解x的线性系统Ax = b，其中A是方阵
print(np.dot(A, x))

A = np.array([[1, 6, 2], [1, 8, 1], [1, 10, 0], [1, 14, 2], [1, 18, 0]])
B = np.array([7, 9, 13, 17.5, 18]).reshape((5,1))
x, residual, rank,  s = np.linalg.lstsq(A, B, rcond = None) # 计算Ax = B的最小二乘解，返回最小二乘解，残差综合，x1矩阵的秩，x1的奇异值
print(x)
print(residual)
print(rank)
print(s)

[[-0.25460766 -0.89797827  0.07345335  1.84753812 -0.86927374]
 [-0.49393928  0.46241715 -0.23280444  0.5548197   1.40467306]
 [ 1.49789294  0.5919186   0.39498196  0.90072838  0.29802494]
 [-1.32554101 -1.3795442  -2.05795686 -0.23477806  0.98839038]
 [ 0.47777235  0.51012667 -0.9388988  -0.79863155  2.58057061]]
[[ 4.53780975  2.95922367  2.9672565   0.53439395 -0.1033167 ]
 [ 2.95922367  3.53393364  2.42027002 -0.95284961  1.55943004]
 [ 2.9672565   2.42027002  5.33232146  1.59531215 -4.73011013]
 [ 0.53439395 -0.95284961  1.59531215  5.22546671 -2.85121404]
 [-0.1033167   1.55943004 -4.73011013 -2.85121404 10.45382232]]
[[  0.63901029  -1.17184136   0.58698947  -0.25198971   0.37799315]
 [ -1.17184136  13.81984784 -12.71405152   2.64487174  -7.10457121]
 [  0.58698947 -12.71405152  12.45898021  -2.42965493   6.87712109]
 [ -0.25198971   2.64487174  -2.42965493   0.73391934  -1.29622458]
 [  0.37799315  -7.10457121   6.87712109  -1.29622458   3.91740551]]
[ 4.53780975  3.53393364  5

一次性模拟多次随机漫步

In [37]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps))
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)
print(walks)
hits30 = (np.abs(walks) >= 30)
print(hits30.shape)
hits30 = hits30.any(1)
print(hits30.shape)
print(hits30.sum())  # 达到30 或者-30 的数字

crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
print(crossing_times.mean())

[[ -1   0  -1 ... -36 -35 -36]
 [ -1   0  -1 ...  16  17  18]
 [  1   2   3 ... -52 -51 -50]
 ...
 [  1   2   1 ... -50 -49 -48]
 [  1   2   1 ...  10   9   8]
 [ -1  -2  -3 ... -12 -13 -14]]
(5000, 1000)
(5000,)
3410
507.09560117302055
