In [1]:
import pandas as pd
import numpy as np

In [7]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2001, 2002, 2003],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)  # 利用包含等长度列表或者Numpy 数组的字典来形成DataFrame
print(frame)

frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],  # columns: 指定列名  index: 指定行名
                     index = ['one', 'two', 'three', 'four', 'five', 'six'])
print(frame2)

frame2['debt'] = np.arange(6.)
print(frame2)
val = pd.Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])  # series的索引会按照DataFrame的索引重新排序，并在孔雀的地方填充缺失值
frame2['debt'] = val
print(frame2)

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2
       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN
       year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0
       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN


普通的Python 切片中是不包含尾部的，Series 的切片与之不同，包含头部和尾部

In [8]:
obj = pd.Series(np.arange(5.), index = ['a', 'b', 'c', 'd', 'e'])

print(obj)
print(obj['b':'e'])  

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64


在pandas 对象使用整数索引对新用户来说经常会产生歧义，这是因为它和在列表、元组等Python 内建数据结构上进行索引有些许不同。例如，下面的代码会产生错误：

In [9]:
ser = pd.Series(np.arange(3.))
print(ser)
print(ser[-1])

0    0.0
1    1.0
2    2.0
dtype: float64


KeyError: -1

在上面的例子中，pandas可以“回退”到整数索引，但是这样的方式难免会引起一些微小的错误。假设我们有一个索引，它包含了0、1、2，但是推断用户所需要的索引（标签索引或位置索引）是很难的。
另一方面，对于非整数索引，则不会有潜在的歧义：

In [10]:
ser2 = pd.Series(np.arange(3.), index = ['a', 'b', 'c'])

print(ser2)
print(ser2[-1])

a    0.0
b    1.0
c    2.0
dtype: float64
2.0


所以为了更精确处理，可以使用loc（用于标签）或iloc（用于整数）

In [11]:
print(ser[:1])  # 取ser第0行

print(ser.loc[:1]) # 取ser第0、1行，包含尾部==》用于标签

print(ser.iloc[:1]) #取ser第0行==》用于整数

0    0.0
dtype: float64
0    0.0
1    1.0
dtype: float64
0    0.0
dtype: float64


DataFrame 算术和数据对齐

In [15]:
df1 = pd.DataFrame(np.arange(12.).reshape(3, 4), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape(4, 5), columns=list('abcde'))
print(df1)
print(df2)

print(df1.add(df2, fill_value = 0)) # df1 + df2
print(df1.radd(df2, fill_value = 0)) # df2 + df1

print(df1.div(df2, fill_value = 0)) # df1 / df2
print(df1.rdiv(df2, fill_value = 0)) # df2 / df1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0
      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0
      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0
     a         b         c         d    e
0  NaN  1.000000  1.000000  1.000000  0.0
1  0.8  0.833333  0.857143  0.875000  0.0
2  0.8  0.818182  0.833333  0.846154  0.0
3  0.0  0.000000  0.000000  0.000000  0.0
          a         b         c         d    e
0       NaN  1.000000  1.000000  1.000000  inf
1  1.250000  1.200000  1.166667  1.142857  inf
2  1.250000  1.222222  1.200000  1.181818  inf
3       inf       inf     

DataFrame 的排序和排名

In [5]:
frame = pd.DataFrame({'b':[4, 7, -3, 2], 'a':[0, 1, 0, 1]})
print(frame)

print(frame.sort_index(axis=1, ascending=True)) # axis选择排序轴，accending升降序
print(frame.sort_values(by = 'b')) # 根据b列排序
print(frame.sort_values(by = ['b', 'a'])) # 'b'主排序，'a'副排序

obj =  pd.Series([7, -5, 7, 4, 2, 0, 4])
print(obj.rank())  # 默认情况下，rank通过将平均排名分配到每个组来打破平级关系
print(obj.rank(method='min'))  # 对整个组使用最小排名
print(obj.rank(method='max'))  # 对整个组使用最大排名
print(obj.rank(method='first')) # 按照值在数据中出现的次序分配排名
print(obj.rank(method='dense'))  # 类似method = 'min'，但组间排名总是增加1，而不是一个组中的相等元素的数量

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1
   a  b
0  0  4
1  1  7
2  0 -3
3  1  2
   b  a
2 -3  0
3  2  1
0  4  0
1  7  1
   b  a
2 -3  0
3  2  1
0  4  0
1  7  1
0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64
0    6.0
1    1.0
2    6.0
3    4.0
4    3.0
5    2.0
6    4.0
dtype: float64
0    7.0
1    1.0
2    7.0
3    5.0
4    3.0
5    2.0
6    5.0
dtype: float64
0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64
0    5.0
1    1.0
2    5.0
3    4.0
4    3.0
5    2.0
6    4.0
dtype: float64


比较numpy与pandas在轴上的处理:pandas保持了numpy对关键字axis的用法。形象记忆，将选中axis轴压成一维

In [9]:
arr = np.random.randn(5, 4)
print(arr)
print(arr.mean(axis = 1))
frame = pd.DataFrame(arr, index=['a', 'b','c', 'd', 'e'], columns=['one', 'two', 'three', 'four'])
print(frame)
print(frame.mean(axis = 1))

[[ 2.41786546e-03 -1.20948666e+00 -2.01083049e-01  4.66862976e-01]
 [ 1.12151813e+00 -7.21432368e-01 -8.27848665e-01 -1.82533464e-01]
 [ 5.58864635e-01 -4.35180867e-01 -1.38077296e+00 -2.67759273e+00]
 [-7.82841761e-01 -5.43747663e-01  5.74670687e-01  6.46724818e-01]
 [ 5.26498667e-01  8.92096026e-01 -1.55296641e+00  1.18242779e+00]]
[-0.23532222 -0.15257409 -0.98367048 -0.02629848  0.26201402]
        one       two     three      four
a  0.002418 -1.209487 -0.201083  0.466863
b  1.121518 -0.721432 -0.827849 -0.182533
c  0.558865 -0.435181 -1.380773 -2.677593
d -0.782842 -0.543748  0.574671  0.646725
e  0.526499  0.892096 -1.552966  1.182428
a   -0.235322
b   -0.152574
c   -0.983670
d   -0.026298
e    0.262014
dtype: float64


DataFrame 唯一值、技术和集合成员属性方法测试

In [26]:
arr = [[1, 3, 4, 3, 4],
       [2, 3, 1, 2, 3],
       [1, 5, 2, 4, 4]]
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
print(data)
print(data['Qu1'].isin([1, 3])) # isin 计算表征Series中每个值是否包含于传入序列的布尔值数组
print(data['Qu1'].unique())
print(data['Qu1'].value_counts())

# 计算DataFrame 多个相关列的直方图，行标签是所有列出现的不同值，数值则是这些不同值在每列中出现的次数
result = data.apply(pd.value_counts).fillna(0)
print(result)

   Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4
0     True
1     True
2    False
3     True
4    False
Name: Qu1, dtype: bool
[1 3 4]
4    2
3    2
1    1
Name: Qu1, dtype: int64
   Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0
